kafka:
  clusters:
    - name: console-kafka
      namespace: ${NAMESPACE}
      listener: ${NAMESPACE}
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        bootstrap.servers: my-kafka1.cloud.example.com:9093
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka1-user" password="sCr@m!";
      adminProperties: {}
      consumerProperties: {}
      producerProperties: {}
