kafka:
  clusters:
    - name: console-kafka
      namespace: "${NAMESPACE}"
      listener: secure
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        bootstrap.servers: bootstrap."${BOOTSTRAP_DOMAIN}"
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="console-kafka-user1" password="${KAFKA_USER_PASSWORD}";
      adminProperties: {}
      consumerProperties: {}
      producerProperties: {}