on:
  pull_request:
    branches:
      - main

jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:

      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          cpus: 4
          memory: 4096m

      - name: Create namespace
        run: kubectl create namespace console-namespace

      - name: Install Strimzi
        run: kubectl create -f 'https://strimzi.io/install/latest?namespace=console-namespace' --namespace=console-namespace

      - name: Create Kafka
        run: kubectl apply -f https://strimzi.io/examples/latest/kafka/kraft/kafka-single-node.yaml --namespace=console-namespace

      - name: Wait for Kafka
        run: kubectl wait kafka/my-cluster --for=condition=Ready --timeout=300s --namespace=console-namespace