on:
  pull_request:
    branches:
      - main

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          cpus: 4
          memory: 4000m
      - name: check memory
        run: minikube config get memory
      - name: check cpu
        run: minikube config get cpus