name: Greeting on variable day

on:
  pull_request:
    branches:
      - main

env:
  TARGET_NAMESPACE: console-namespace
jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          curl -L https://github.com/mikefarah/yq/releases/download/v4.2.1/yq_linux_amd64 > yq && chmod +x yq
          sudo cp -v yq /usr/bin/

      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          cpus: 4
          memory: 4096m

      - name: Enable ingress
        run: minikube addons enable ingress && minikube addons enable ingress-dns

      - name: Export IP
        run: echo "CLUSTER_DOMAIN=$(minikube ip)" >> $GITHUB_ENV

      - name: Show IP
        run: echo $CLUSTER_DOMAIN

      - name: Create namespace
        run: kubectl create namespace $TARGET_NAMESPACE

      - name: Install Strimzi
        run: kubectl create -f https://strimzi.io/install/latest?namespace=$TARGET_NAMESPACE -n $TARGET_NAMESPACE

      - name: Show pods
        run: kubectl get pods -n $TARGET_NAMESPACE

      - name: Show dir
        run: pwd

      - name: Show files
        run: ls

      - name: Console installation
        shell: bash
        run: |
          cd ./install/
          ./001-deploy-prometheus.sh $TARGET_NAMESPACE $CLUSTER_DOMAIN
          ./002-deploy-console-kafka.sh $TARGET_NAMESPACE $CLUSTER_DOMAIN zk
          
          sed -i 's#""#"$(kubectl get secret console-user -o yaml | yq '.data.password' - | base64 --decode)"#g' $INSTALL_DIR/resources/console/console-config.yaml
          
          ./003-install-console.sh $TARGET_NAMESPACE $CLUSTER_DOMAIN $INSTALL_DIR/resources/console/console-config.yaml

      - name: Wait for Kafka
        run: kubectl wait kafka/my-cluster --for=condition=Ready --timeout=300s -n $TARGET_NAMESPACE

      - name: Show pods
        run: kubectl get pods -n $TARGET_NAMESPACE