on:
  pull_request:
    branches:
      - main

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: kubectl
        run: kubectl get pods -A